### PR TITLE
[FIX] base64 decode on base64url generated tokens

### PR DESCRIPTION
**Pull request by rgericke-elb**
Fixes an issue where base64_decode returns an invalid json string when the token got e.g. base64url encoded.
I also refactored a variable name because the current implementation lead to an overridden method parameter.

### CODE REVIEW

**Comment by rgericke-elb** [comment]
Thank you for merging so quickly. Would it be possible to create a bugfix release for this issue?

**Comment by theroch** [comment]
No problem. I've released v1.0.1.0

**Comment by rgericke-elb** [comment]
Hey, thank you for creating the release so quickly. Could you please also update the package on packagist.org so i can actually use it in composer? Thanks in advance.

**Comment by theroch** [comment]
Hey, thank you to point me to the problem with packagist. I've missed updating the version in composer.json. The new release is now available on packagist.

**Pull request merged**
